### ISSUE TITLE
issues w/ markbot

### ISSUE THREAD

**Issue by MoonaBarbuzza** [MoonaBarbuzza/stacked-nav#3]
Hi Thomas,

I have been running this folder through Markbot several time, I have been able to rid most the errors, but many remain, cant seem to correct them. 
for example: expected to see this element: header
expected to see this element: header h1 
expected to see this element: header nav
expected to see this element: header nav ul
expected to see this element: header nav ul li

then: expected to see body selector
and finally: Line 26. End of file reached when inside an attribute value. Ignoring tag.

thanks in advance,

Moona

@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you synced your code recently in the GitHub app?
The code that's there looks out-of-date.

**Comment by MoonaBarbuzza** [comment]
oops, I think i forgot to do that. Sorry!

**Comment by thomasjbradley** [comment]
I remember yesterday you mentioning that the CSS wasn't working because of a funny quote.

It seems to have come back, on this line of your code:
https://github.com/MoonaBarbuzza/stacked-nav/blob/gh-pages/index.html#L7

I think that's what's causing the problems.
