### ISSUE TITLE
css in horizontal nav not linking 

### ISSUE THREAD

**Issue by MoonaBarbuzza** [MoonaBarbuzza/stacked-nav#4]
I put in the link for stylesheet, and viewport, in html.
 But nothing happen when I try to make style in css. Its not reacting to any asthetic changes. :( Cannot seem to locate the problem.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Sorry, I can't sse the code.
Make sure you've committed it and synced it in the GitHub app.

**Comment by MoonaBarbuzza** [comment]
Sorry about that. I commit a few minutes ago. I manage to fix the error. It was an open quotation mark that didnt match the closing one. So now css is workng fine.

**Comment by thomasjbradley** [comment]
Great!
